steps:
  # Get ssh key from Google Secret Manager
  - name: gcr.io/cloud-builders/gcloud
    id: sshkey
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=ortelius-github > /root/.ssh/id_rsa;chmod 600 /root/.ssh/id_rsa;ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts' ]
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: gcr.io/cloud-builders/docker
    id: cloudbuild_sh
    entrypoint: 'bash'
    args: ['-c', 'ls -A1 | xargs rm -rf;git clone $$COMPONENT_GITURL .;git checkout --track -b $BRANCH_NAME origin/$BRANCH_NAME;env | sed "s/^/export /" >> /workspace/cloudbuild.sh']
    volumes:
    - name: 'ssh'
      path: /root/.ssh
    env: 
      - 'COMPONENT_GITURL=git@github.com:ortelius/test-database.git'
      - 'COMPONENT_VARIANT=$BRANCH_NAME'
      - 'COMPONENT_VERSION=9.0.0'
      - 'COMPONENT_VERSION_COMMIT="v$$COMPONENT_VERSION.$$(git rev-list --count $BRANCH_NAME)-g$SHORT_SHA"'
      - 'COMPONENT_DOCKERREPO=quay.io/ortelius/test-database'
      - 'IMAGE_TAG="$BRANCH_NAME-v$$COMPONENT_VERSION.$$(git rev-list --count $BRANCH_NAME)-g$SHORT_SHA"'

  # Login to Quay for push.
  - name: 'gcr.io/cloud-builders/docker'
    id: login
    entrypoint: 'bash'
    args: ['-c', '. /workspace/cloudbuild.sh;docker login quay.io --username "$$QUAY_USERID" --password $$QUAY_PASSWORD']
    secretEnv: ['QUAY_USERID', 'QUAY_PASSWORD']     
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'

  # Build the test-database image
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    entrypoint: 'bash'
    args: ["-c", '. /workspace/cloudbuild.sh;docker build --tag $$COMPONENT_DOCKERREPO:$$IMAGE_TAG --tag $$COMPONENT_DOCKERREPO:latest -f /workspace/Dockerfile .']
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'

  # Run the container-structure-tests
  - name: 'gcr.io/gcp-runtimes/container-structure-test'
    id: structure-test
    args: ['test', '--image', '${_COMPONENT_DOCKERREPO}:${_IMAGE_TAG}', '--config', 'cst/config.yaml']

  # Push the test-database image
  - name: 'gcr.io/cloud-builders/docker'
    id: push
    entrypoint: 'bash'
    args: ["-c", '. /workspace/cloudbuild.sh;docker push $$COMPONENT_DOCKERREPO:$$IMAGE_TAG;docker push $$COMPONENT_DOCKERREPO:latest']
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'

substitutions:
    '_COMPONENT_DOCKERREPO=quay.io/ortelius/test-database'
    '_IMAGE_TAG="$BRANCH_NAME-v9.0.0.$$(git rev-list --count $BRANCH_NAME)-g$SHORT_SHA"'

secrets:
- kmsKeyName: projects/eighth-physics-169321/locations/global/keyRings/cli/cryptoKeys/quay
  secretEnv:
    QUAY_USERID: CiQAW+P1J9UZz+Hr1uonladAW2dKqaiVd5ux8Q9EV81pK0u5V+4SNACcBdnKacvH4QXPamH1N4uJZvZ/0TMwvELgXAAlP0wR2zBw2WhCV82GMiUkW3iGVlbqz7c=
- kmsKeyName: projects/eighth-physics-169321/locations/global/keyRings/cli/cryptoKeys/quay-pw
  secretEnv:
    QUAY_PASSWORD: CiQAUULEud9Ej8XtwNAb9gkbDVhSGFZYhUGE30fNwR+7ehAOkH8SMgCz6KYeykjgS16RPxgKlrIQL/1TKDt06v4OXGIisFXOkdWC+jvdda8mTzVNCi8sT5g6 
